version: '2'

services:
  gpsd:
    build:
      context: .
      dockerfile: Dockerfile_gpsd
    devices:
      - /dev/ttyACM0
    restart: always
#   ports:
#     - 2947:2947
  ntpd:
    build:  
      context: .
      dockerfile: Dockerfile_ntp
    volumes:
      - ./ntp.conf:/etc/ntp.conf:ro
    links:
      - gpsd
    ports:
      - 123:123/udp
    restart: always

