global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

  # A scrape configuration containing exactly one endpoint to scrape:
  # Here it's Prometheus itself.

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - 'alertmanager:9093'

rule_files:
  - 'alert.rules'

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'docker_host'
    
    scrape_interval: 5s

    static_configs:
      - targets: ['container_exporter:9104']
    
  - job_name: 'snmp_routers'
    static_configs:
      - targets:
        - 10.228.16.129
        - 10.228.19.81
        - 10.228.19.65
        - 10.228.17.1
    metrics_path: /snmp
    params:
      module: [default_mikrotik]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp_exporter:9116
  
  - job_name: 'snmp_antenes'
    static_configs:
      - targets:
        - 10.228.28.10
        - 10.228.17.247
        - 10.228.28.8
        - 10.228.16.137
        - 10.228.17.243
    metrics_path: /snmp
    params:
      module: [default_v1]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp_exporter:9116
