version: '2'
services:
  dns_recursive:
    build: .
    ports:
     - "53:53"
     - "53:53/udp"
    volumes:
     - ./named.conf:/etc/bind/named.conf:ro
     - ./zones/:/etc/bind/zones/:ro
    restart: always
